// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzuhzmZhwgSwjImOTy4Cmu7xQExAPlqI',
    appId: '1:1067626187837:web:ff9b53cce376535fbeae54',
    messagingSenderId: '1067626187837',
    projectId: 'instagram-flutter-clone-324cc',
    authDomain: 'instagram-flutter-clone-324cc.firebaseapp.com',
    storageBucket: 'instagram-flutter-clone-324cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaEbGInmy0LDPiGXdq9W65XRcMWOtqj94',
    appId: '1:1067626187837:android:b8ae62f48ee9d121beae54',
    messagingSenderId: '1067626187837',
    projectId: 'instagram-flutter-clone-324cc',
    storageBucket: 'instagram-flutter-clone-324cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQgafwC0TojqIcwp_pUK2_uDjD7R_qU7s',
    appId: '1:1067626187837:ios:c230c6f7e3488668beae54',
    messagingSenderId: '1067626187837',
    projectId: 'instagram-flutter-clone-324cc',
    storageBucket: 'instagram-flutter-clone-324cc.appspot.com',
    iosBundleId: 'com.example.instagramFlutterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQgafwC0TojqIcwp_pUK2_uDjD7R_qU7s',
    appId: '1:1067626187837:ios:d882a63a07b635dbbeae54',
    messagingSenderId: '1067626187837',
    projectId: 'instagram-flutter-clone-324cc',
    storageBucket: 'instagram-flutter-clone-324cc.appspot.com',
    iosBundleId: 'com.example.instagramFlutterClone.RunnerTests',
  );
}
